server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: job
  datasource:
    url: jdbc:mysql://localhost:3306/job_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  access-key: "xn6j08mmk782qbf8iun443h92tloi83tci3mibe9yemiek4hgrqn50yp9k0idz1p"
  refresh-key: "r7gk2v9xq1m3z8n4t5b6w0eudcylpohfajskgqzvnmxrtwcbieo7l2p9h3udkq0m"
  expiration:
    access-token: 3600000
    refresh-token: 604800000
file:
  upload-dir: D:\assignments\CT250\job-backend\uploads